// usage: pnpm tsx scripts/seed-editorial-calendar.ts > migrations/0011_editorial_calendar_seed.sql
import { ulid } from 'ulid';

const START = new Date('2026-05-06');
const DAYS = 90;

interface Row {
  id: string; start_date: string; end_date: string;
  theme: string; cuisine_filter: string | null;
  weight: number; notes: string | null;
}

const rows: Row[] = [];

for (let i = 0; i < DAYS; i++) {
  const d = new Date(START);
  d.setUTCDate(d.getUTCDate() + i);
  const ymd = d.toISOString().slice(0, 10);
  const dow = d.getUTCDay();
  const month = d.getUTCMonth() + 1;

  let theme: string;
  if (dow >= 1 && dow <= 4) theme = 'weeknight_dinners';
  else if (dow === 5 || dow === 6) theme = 'comfort_food_or_indulgence';
  else theme = 'meal_prep_sunday';

  rows.push({
    id: ulid(), start_date: ymd, end_date: ymd, theme,
    cuisine_filter: null, weight: 1.0,
    notes: 'auto-seeded base rotation',
  });

  let seasonal: string | null = null;
  if (month >= 5 && month <= 6) seasonal = 'summer_freshness';
  else if (month >= 11 && month <= 12) seasonal = 'festive_holiday';
  else if (month === 1) seasonal = 'healthy_january';
  else if (month === 7 || month === 8) seasonal = 'cookout_weeknights';

  if (seasonal) {
    rows.push({
      id: ulid(), start_date: ymd, end_date: ymd, theme: seasonal,
      cuisine_filter: null, weight: 1.5, notes: 'seasonal overlay',
    });
  }
}

const lines = ['-- Auto-generated by scripts/seed-editorial-calendar.ts'];
lines.push('-- Window: 90 days from 2026-05-06');
lines.push('');
lines.push(`INSERT INTO social_editorial_calendar (id, start_date, end_date, theme, cuisine_filter, weight, notes) VALUES`);
const valuesLines = rows.map((r, i) => {
  const last = i === rows.length - 1 ? ';' : ',';
  const cuisine = r.cuisine_filter === null ? 'NULL' : `'${r.cuisine_filter}'`;
  const notes = r.notes === null ? 'NULL' : `'${r.notes.replace(/'/g, "''")}'`;
  return `('${r.id}', '${r.start_date}', '${r.end_date}', '${r.theme}', ${cuisine}, ${r.weight}, ${notes})${last}`;
});
console.log([...lines, ...valuesLines].join('\n'));
